# Generated by Django 5.2.14 on 2026-05-30 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('exercises', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('treatment_type', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('progress_evaluation', models.TextField(blank=True)),
                ('pain_level_before', models.PositiveIntegerField(blank=True, help_text='0-10 scale', null=True)),
                ('pain_level_after', models.PositiveIntegerField(blank=True, help_text='0-10 scale', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_record', to='appointments.appointment')),
                ('exercises_performed', models.ManyToManyField(blank=True, to='exercises.exercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sessions', to='patients.patient')),
                ('physiotherapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
